export const tiposIngreso      = ["INMUEBLE","VEHICULO","SUCURSALES","INVERSIONES","NORMA - MASAJES","OTROS"];
export const inmuebles         = ["DPTO CIUDAD DE LA PAZ","DPTO CORRIENTES","DPTO CONESA I","DPTO CONESA II"];
export const sucursales        = ["PRANA","EQUILIBRIO","FOUR SEASONS","MASAJES EN DOMICILIO","MASAJES A DOMICILIO"];
export const mediosIngreso     = ["EFECTIVO","CHEQUE","TARJETA DE CREDITO","TARJETA DE DEBITO","BILLETERA VIRTUAL","TRANSFERENCIA","ACREDITACION","OTROS"];
export const categoriasIngreso = ["SERVICIO","ALQUILER","INVERSIONES","OTROS"];

export const tiposEgreso       = ["INMUEBLE","VEHICULO","SUCURSALES","JUBILACION","OTROS"];
export const mediosEgreso      = ["EFECTIVO","CHEQUE","TARJETA DE CREDITO","TARJETA DE DEBITO","BILLETERA VIRTUAL","TRANSFERENCIA","OTROS"];
export const categoriasEgreso  = ["SERVICIO","SUELDOS","PRODUCTOS DE LIMPIEZA","PRODUCTOS DE MASAJE","VEHÍCULO","SEGUROS","OTROS"];